coverage:
  precision: 2
  round: down
  range: "60...90"

  status:
    project:
      default: on
    patch:
      default: on
    changes:
      default: on

codecov:
  branch: develop

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
