language: elixir

otp_release:
  - 20.2
before_install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - wget https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - tar xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - sudo mv wkhtmltox/bin/wkhtmltopdf /usr/bin
script:
  - set -e
  - MIX_ENV=test mix format --check-formatted
  - set +e
  - mix coveralls.json --umbrella
after_script:
  - bash <(curl -s https://codecov.io/bash)
  - bash .scripts/inch_report.sh

matrix:
  include:
  - elixir: "1.7.2"
    script:
      - mix coveralls.json --umbrella

addons:
  postgresql: "9.5"

env:
  global:
    - FRONTEND_CHECKOUT_URL=http://localhost:4200/checkout/
    - HOSTED_PAYMENT_URL=http://localhost:3000/api/v1/hosted-payment/

notifications:
  email:
    recipients:
      - ananya95+travis@gmail.com

